// <auto-generated />
using System;
using DailyReportMemoApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyReportMemoApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("DailyReportMemoApp.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.HasIndex("CompanyName");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.CompanyProject", b =>
                {
                    b.Property<int>("CompanyProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyProjectId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("CompanyId", "ProjectId")
                        .IsUnique();

                    b.ToTable("CompanyProjects", (string)null);
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectName");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.ProjectTaskItem", b =>
                {
                    b.Property<int>("ProjectTaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectTaskItemId");

                    b.HasIndex("TaskItemId");

                    b.HasIndex("CompanyProjectId", "TaskItemId")
                        .IsUnique();

                    b.ToTable("ProjectTaskItems", (string)null);
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.SpecialTask", b =>
                {
                    b.Property<int>("SpecialTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultStartFlg")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialTaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SpecialTaskId");

                    b.ToTable("SpecialTasks", (string)null);
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskItemId");

                    b.HasIndex("TaskItemName");

                    b.ToTable("TaskItems", (string)null);
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.WorkLog", b =>
                {
                    b.Property<int>("WorkLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectTaskItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpecialTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkingOnId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkLogId");

                    b.HasIndex("ProjectTaskItemId");

                    b.HasIndex("SpecialTaskId");

                    b.HasIndex("WorkingOnId");

                    b.ToTable("WorkLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkLogs_TaskType", "(\"ProjectTaskItemId\" IS NOT NULL AND \"SpecialTaskId\" IS NULL)\r\nOR\r\n(\"ProjectTaskItemId\" IS NULL AND \"SpecialTaskId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.WorkTimeRange", b =>
                {
                    b.Property<int>("WorkTimeRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkLogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkTimeRangeId");

                    b.HasIndex("WorkLogId");

                    b.ToTable("WorkTimeRanges", (string)null);
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.WorkingOn", b =>
                {
                    b.Property<int>("WorkingOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WorkingOnEnd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WorkingOnFlg")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WorkingOnStart")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkingOnId");

                    b.HasIndex("WorkDate");

                    b.ToTable("WorkingOnLogs", (string)null);
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.CompanyProject", b =>
                {
                    b.HasOne("DailyReportMemoApp.Models.Company", "Companies")
                        .WithMany("CompanyProjects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DailyReportMemoApp.Models.Project", "Projects")
                        .WithMany("CompanyProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Companies");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.ProjectTaskItem", b =>
                {
                    b.HasOne("DailyReportMemoApp.Models.CompanyProject", "CompanyProjects")
                        .WithMany("ProjectTaskItems")
                        .HasForeignKey("CompanyProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DailyReportMemoApp.Models.TaskItem", "TaskItems")
                        .WithMany("ProjectTaskItems")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyProjects");

                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.WorkLog", b =>
                {
                    b.HasOne("DailyReportMemoApp.Models.ProjectTaskItem", "ProjectTaskItems")
                        .WithMany("WorkLogs")
                        .HasForeignKey("ProjectTaskItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DailyReportMemoApp.Models.SpecialTask", "SpecialTasks")
                        .WithMany("WorkLogs")
                        .HasForeignKey("SpecialTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DailyReportMemoApp.Models.WorkingOn", "WorkingOnLogs")
                        .WithMany("WorkLogs")
                        .HasForeignKey("WorkingOnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProjectTaskItems");

                    b.Navigation("SpecialTasks");

                    b.Navigation("WorkingOnLogs");
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.WorkTimeRange", b =>
                {
                    b.HasOne("DailyReportMemoApp.Models.WorkLog", "WorkLogs")
                        .WithMany("WorkTimeRanges")
                        .HasForeignKey("WorkLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.Company", b =>
                {
                    b.Navigation("CompanyProjects");
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.CompanyProject", b =>
                {
                    b.Navigation("ProjectTaskItems");
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.Project", b =>
                {
                    b.Navigation("CompanyProjects");
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.ProjectTaskItem", b =>
                {
                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.SpecialTask", b =>
                {
                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.TaskItem", b =>
                {
                    b.Navigation("ProjectTaskItems");
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.WorkLog", b =>
                {
                    b.Navigation("WorkTimeRanges");
                });

            modelBuilder.Entity("DailyReportMemoApp.Models.WorkingOn", b =>
                {
                    b.Navigation("WorkLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
